# Generated by Django 2.2 on 2021-12-14 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quote_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_quotes', to='app.User'),
            preserve_default=False,
        ),
    ]
